language: ruby
rvm:
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - ruby-head

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head

script: bundle exec rspec && bundle exec codeclimate-test-reporter

notifications:
  email:
    on_success: change
    on_failure: always
